### ISSUE TITLE
EPIC: Haal Centraal BRP implementatie

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/haal-centraal-brp#1]
#### Epic omschrijving

We kunnen 1 Haal Centraal-aansluiting hebben voor de BRP. Implementeren van een geschikte gateway/proxy die de BRP ontsluit voor achterliggende applicaties. Afnemers zijn bijv.:
- Mijn Nijmegen
- Tribe/BRP
- Yivi
maar ook externe applicatie als de nieuwe BRIKS-applicatie.

Ook de 'protocollering' moet opgelost worden.

#### Gerelateerde issues.

```[tasklist]
### Tasks
- [ ] #2
- [ ] #3
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/5
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/6
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/7
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/9
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/10
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/27
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/30
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/33
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/32
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/54
- [ ] https://github.com/GemeenteNijmegen/haal-centraal-brp/issues/58
```

**Comment by MartijnvDijk** [comment]
BRIKS applicatie is aangesloten
